---
abstract: 'framework for localization'
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.94, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Locale-Maketext
no_index:
  directory:
    - t
    - inc
requires:
  I18N::LangTags: '0.31'
  I18N::LangTags::Detect: '0'
  Test::More: '0'
resources:
  MailingList: http://lists.perl.org/list/perl5-porters.html
  bugtracker: http://rt.perl.org/perlbug/
  license: http://dev.perl.org/licenses/
  repository: http://perl5.git.perl.org/perl.git/tree/HEAD:/dist/Locale-Maketext
version: '1.26'
