--- #YAML:1.0
name:               Locale-Maketext
version:            1.17
abstract:           framework for localization
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    I18N::LangTags:       0.31
    I18N::LangTags::Detect:  0
    Test::More:           0
resources:
    bugtracker:   http://rt.perl.org/perlbug/
    license:      http://dev.perl.org/licenses/
    MailingList:  http://lists.perl.org/list/perl5-porters.html
    repository:   http://perl5.git.perl.org/perl.git/tree/HEAD:/dist/Locale-Maketext
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
