# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Locale-Maketext
version:      1.10
version_from: lib/Locale/Maketext.pm
installdirs:  perl
requires:
    I18N::LangTags:                0.3

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
